# Generated by Django 4.1.6 on 2023-02-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=7),
        ),
    ]
