# Generated by Django 4.1.6 on 2023-02-11 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 11, 21, 55, 18, 706007)),
        ),
    ]
