# Generated by Django 4.1.6 on 2023-02-14 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_refund_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 14, 11, 10, 36, 357258)),
        ),
    ]
